// N cubes => N + 1 grid points
#define BLOCK_SIZE 31
#define BLOCK_RESOLUTION (BLOCK_SIZE + 1)
#define BLOCK_PADDING 8
#define BLOCK_PADDED_RESOLUTION (BLOCK_RESOLUTION + 2 * BLOCK_PADDING)
#define BLOCK_POOL_SIZE 100
#define PI 3.14159265f

#define VIEW_RANGE 16

#define FOG_MULTIPLIER 1.1
#define FOG_BIAS 0.2

#define ONE_BLOCK_PROFILE false
